# go-11-052-测试多返回值函数的错误

Go会用到返回值来表达执行是否成功，

1. 成功——一般返回ture

   失败——一般是返回零值（或 nil）和 false

2. 当不使用 true 或 false 的时候，

   也可以使用一个 error 类型的变量来代替作为第二个返回值：

   成功执行的话，error 的值为 nil，否则就会包含相应的错误信息，例如Go 语言中的错误类型为 error: `var err error`



这需要用if-else结构来执行测试结果。

（由于其符号的原因，这样的形式又称之为 comma,ok 模式（pattern））



**<u>一个复习</u>**

**字符串类型转化为数字类型的函数：**

1. `strconv.Atoi(s string) (i int, err error)` 将字符串转换为 int 型。
2. `strconv.ParseFloat(s string, bitSize int) (f float64, err error)` 将字符串转换为 float64 型。

利用多返回值的特性，这些函数会返回 2 个值，

<u>第 1 个是转换后的结果（如果转换成功）</u>，**<u>第 2 个是可能出现的错误</u>，**

因此，我们一般使用以下形式来进行从字符串到其它类型的转换：

	val, err = strconv.Atoi(s)

函数 `strconv.Atoi` 的作用是将一个字符串转换为一个整数。

之前我们忽略了相关的错误检查，就像下面这样,

第 2 个返回值是可能出现的错误，直接用_下划线抛弃了：

```go
anInt, _ = strconv.Atoi(origStr)
```

如果 origStr 不能被转换为整数，anInt 的值会变成 0 而 `_` 无视了错误，程序会继续运行。

**这样做非常不好**



第二个版本中对代码进行了改进：

```GO
package main

import (
	"fmt"
	"strconv"
)

func main() {
	var orig string = "ABC"
	// var an int
	var newS string
	// var err error

	fmt.Printf("The size of ints is: %d\n", strconv.IntSize)	//strconv.IntSize用来知晓你这个程序运行的操作系统下的int类型所占的位数
	// anInt, err = strconv.Atoi(origStr)
	an, err := strconv.Atoi(orig)
	if err != nil { //如果err不等于nil空值。
        //!= 意为不等于。nil表示无值，任何变量在没有被赋值之前的值都为nil，对于真假判断，只有nil与false、0表示假，其余均为真。
		fmt.Printf("orig %s is not an integer - exiting with error\n", orig)
		return //怎么后面要跟一个return，如果确实存在错误，则会打印相应的错误信息然后通过 `return` 提前结束函数的执行。
	} 
	fmt.Printf("The integer is %d\n", an)
	an = an + 5
	newS = strconv.Itoa(an) // `stronv.Itoa（i int） string`可以返回数字i所表示的类型的十进制的数，此处的(i int)指int类型的名为i的值
	fmt.Printf("The new string is: %s\n", newS)
}
```

`if err != nil`这是测试 err 变量是否包含一个真正的错误的习惯用法。

如果确实存在错误，则会打印相应的错误信息然后通过 `return` 提前结束函数的执行。

我们还可以使用携带返回值的 return 形式，例如 `return err`。这样一来，函数的调用者就可以检查函数执行过程中是否存在错误了。





**习惯用法**

```go
value, err := pack1.Function1(param1) //后半截是一个例子意味调用一个会返回两个值的包，就像是上面的strconv.IntSize
if err != nil { //如果err不等于nil空值
	fmt.Printf("An error occured in pack1.Function1 with parameter %v", param1)
	return err
}
// 未发生错误，继续执行：
```

由于本例的函数调用者属于 main 函数，所以程序会直接停止运行。





<u>**如果我们想要在错误发生的同时终止程序的运行，我们可以使用 `os` 包的 `Exit` 函数：**</u>

**此处介绍一种习惯用法**

```go
if err != nil {
	fmt.Printf("Program stopping with error %v", err)
	os.Exit(1)
}
```

（此处的退出代码 1 可以使用外部脚本获取到）

有时候，你会发现这种习惯用法被连续重复地使用在某段代码中。

如果没有错误发生，那么代码就会继续运行，就不需要else来做不符合if后的条件的预案。

有错误发生时，就会用`os.Exit(1)`来退出运行。



<u>**示例 2**</u>：我们尝试通过 `os.Open` 方法打开一个名为 `name` 的只读文件：

```go
f, err := os.Open(name)//倘若正确就会返回值赋给f，倘若错误，就会给err赋值提示错误。
if err != nil { //此处指err不等于nil（空值），意味着err被赋值，也就意味着程序发生了错误。
	return err
}
doSomething(f) // 当没有错误发生时，文件对象被传入到某个函数中，此处的doSomething() 指的是某个函数。
doSomething
```



<u>**示例 3**</u>：可以将错误的获取放置在 if 语句的初始化部分：

**习惯用法**

```go
if err := file.Chmod(0664); err != nil {
	fmt.Println(err)
	return err
}
```



<u>**示例 4**</u>：或者将 ok-pattern 的获取放置在 if 语句的初始化部分，然后进行判断：

**习惯用法**

```go
if value, ok := readData(); ok {
…
}
```

**注意事项**

如果 ， 没有为多返回值的函数准备足够的变量来存放结果：
	

```go
func mySqrt(f float64) (v float64, ok bool) { //后面的那个括号就是指，f，v和ok的数据类型是什么。
	if f < 0 { return } // error case
	return math.Sqrt(f),true
}

func main() {
	t := mySqrt(25.0)
	fmt.Println(t)
}
```

您会得到一个编译错误：`multiple-value mySqrt() in single-value context`。

正确的做法是：

```go
t, ok := mySqrt(25.0)
if ok { fmt.Println(t) }
```

**注意事项 2**

当您将字符串转换为整数时，且确定转换一定能够成功时，

（*atoi* (表示 ascii to integer)是把字符串转换成整型数的一个函数）

可以将 `Atoi` 函数进行一层忽略错误的封装：

```go
func atoi (s string) (n int) {
	n, _ = strconv.Atoi(s)
	return
}
```

实际上，`fmt` 包（第 4.4.3 节）最简单的打印函数也有 2 个返回值：

```go
count, err := fmt.Println(x) // number of bytes printed, nil or 0, error
```

当打印到控制台时，可以将该函数返回的错误忽略；但当输出到文件流、网络流等具有不确定因素的输出对象时，应该始终检查是否有错误发生（另见练习 6.1b）。

# 一个多返回值的例子

Go 原生支持 _多返回值_。 这个特性在 Go 语言中经常用到，例如用来同时返回一个函数的结果和错误信息。

```go
package main

import "fmt"

func vals() (int, int) { //(int, int) 在这个函数中标志着这个函数返回 2 个 int格式的数值。
    return 3, 7 //相当于是直接把3和7变成了int格式，然后返回
}
//此处的返回的本质是vals() (int, int)一整个，通过上面的代码块把这个vals() (int, int)变成了vals() 依次储存着(3, 7)。因为vals()的本质是字典，可以是vals() (int, int, int) ，所以说这个代码块就是为这个字典里的东西赋值，并且按照后一个括号内的数据格式来格式化{}内的return的值
func main() {

    a, b := vals() //这里我们通过 多赋值 操作来使用这两个不同的返回值。
    fmt.Println(a)
    fmt.Println(b)

    _, c := vals() //如果你仅仅需要返回值的一部分的话，你可以使用空白标识符 _。_会直接抛弃此处返回的值。
    fmt.Println(c)
}
```

